// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xbigRat

import "math/big"

// Do executes the test against a []Big_Rat.
func (AllBig_Rat) Do(aa []big.Rat, test func(big.Rat) bool) bool {
	for _, a := range aa {
		if !test(a) {
			return false
		}
	}
	return true
}
