// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xbigRat

// MapBig_Rat contains methods for applying Map tranforms between Big_Rats and other types.
type MapBig_Rat struct{}

// Map provides access to MapBig_Rat methods.
var Map MapBig_Rat
