// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xbigRat

import "math/big"

// ToBool maps a []Big_Rat to a []Bool.
func (MapBig_Rat) ToBool(aa []big.Rat, mapFn func(big.Rat) bool) []bool {
	bb := []bool{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToRune maps a []Big_Rat to a []Rune.
func (MapBig_Rat) ToRune(aa []big.Rat, mapFn func(big.Rat) rune) []rune {
	bb := []rune{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToByte maps a []Big_Rat to a []Byte.
func (MapBig_Rat) ToByte(aa []big.Rat, mapFn func(big.Rat) byte) []byte {
	bb := []byte{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToString maps a []Big_Rat to a []String.
func (MapBig_Rat) ToString(aa []big.Rat, mapFn func(big.Rat) string) []string {
	bb := []string{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt maps a []Big_Rat to a []Int.
func (MapBig_Rat) ToInt(aa []big.Rat, mapFn func(big.Rat) int) []int {
	bb := []int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt8 maps a []Big_Rat to a []Int8.
func (MapBig_Rat) ToInt8(aa []big.Rat, mapFn func(big.Rat) int8) []int8 {
	bb := []int8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt16 maps a []Big_Rat to a []Int16.
func (MapBig_Rat) ToInt16(aa []big.Rat, mapFn func(big.Rat) int16) []int16 {
	bb := []int16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt32 maps a []Big_Rat to a []Int32.
func (MapBig_Rat) ToInt32(aa []big.Rat, mapFn func(big.Rat) int32) []int32 {
	bb := []int32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt64 maps a []Big_Rat to a []Int64.
func (MapBig_Rat) ToInt64(aa []big.Rat, mapFn func(big.Rat) int64) []int64 {
	bb := []int64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat32 maps a []Big_Rat to a []Float32.
func (MapBig_Rat) ToFloat32(aa []big.Rat, mapFn func(big.Rat) float32) []float32 {
	bb := []float32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat64 maps a []Big_Rat to a []Float64.
func (MapBig_Rat) ToFloat64(aa []big.Rat, mapFn func(big.Rat) float64) []float64 {
	bb := []float64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint maps a []Big_Rat to a []Uint.
func (MapBig_Rat) ToUint(aa []big.Rat, mapFn func(big.Rat) uint) []uint {
	bb := []uint{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint8 maps a []Big_Rat to a []Uint8.
func (MapBig_Rat) ToUint8(aa []big.Rat, mapFn func(big.Rat) uint8) []uint8 {
	bb := []uint8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint16 maps a []Big_Rat to a []Uint16.
func (MapBig_Rat) ToUint16(aa []big.Rat, mapFn func(big.Rat) uint16) []uint16 {
	bb := []uint16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint32 maps a []Big_Rat to a []Uint32.
func (MapBig_Rat) ToUint32(aa []big.Rat, mapFn func(big.Rat) uint32) []uint32 {
	bb := []uint32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint64 maps a []Big_Rat to a []Uint64.
func (MapBig_Rat) ToUint64(aa []big.Rat, mapFn func(big.Rat) uint64) []uint64 {
	bb := []uint64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex64 maps a []Big_Rat to a []Complex64.
func (MapBig_Rat) ToComplex64(aa []big.Rat, mapFn func(big.Rat) complex64) []complex64 {
	bb := []complex64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex128 maps a []Big_Rat to a []Complex128.
func (MapBig_Rat) ToComplex128(aa []big.Rat, mapFn func(big.Rat) complex128) []complex128 {
	bb := []complex128{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUintptr maps a []Big_Rat to a []Uintptr.
func (MapBig_Rat) ToUintptr(aa []big.Rat, mapFn func(big.Rat) uintptr) []uintptr {
	bb := []uintptr{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToError maps a []Big_Rat to a []Error.
func (MapBig_Rat) ToError(aa []big.Rat, mapFn func(big.Rat) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Int maps a []Big_Rat to a []Big_Int.
func (MapBig_Rat) ToBig_Int(aa []big.Rat, mapFn func(big.Rat) big.Int) []big.Int {
	bb := []big.Int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Float maps a []Big_Rat to a []Big_Float.
func (MapBig_Rat) ToBig_Float(aa []big.Rat, mapFn func(big.Rat) big.Float) []big.Float {
	bb := []big.Float{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Rat maps a []Big_Rat to a []Big_Rat.
func (MapBig_Rat) ToBig_Rat(aa []big.Rat, mapFn func(big.Rat) big.Rat) []big.Rat {
	bb := []big.Rat{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
