// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xbigInt

// MapBig_Int contains methods for applying Map tranforms between Big_Ints and other types.
type MapBig_Int struct{}

// Map provides access to MapBig_Int methods.
var Map MapBig_Int
