// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xbigInt

import "math/big"

// ToBool maps a []Big_Int to a []Bool.
func (MapBig_Int) ToBool(aa []big.Int, mapFn func(big.Int) bool) []bool {
	bb := []bool{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToRune maps a []Big_Int to a []Rune.
func (MapBig_Int) ToRune(aa []big.Int, mapFn func(big.Int) rune) []rune {
	bb := []rune{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToByte maps a []Big_Int to a []Byte.
func (MapBig_Int) ToByte(aa []big.Int, mapFn func(big.Int) byte) []byte {
	bb := []byte{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToString maps a []Big_Int to a []String.
func (MapBig_Int) ToString(aa []big.Int, mapFn func(big.Int) string) []string {
	bb := []string{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt maps a []Big_Int to a []Int.
func (MapBig_Int) ToInt(aa []big.Int, mapFn func(big.Int) int) []int {
	bb := []int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt8 maps a []Big_Int to a []Int8.
func (MapBig_Int) ToInt8(aa []big.Int, mapFn func(big.Int) int8) []int8 {
	bb := []int8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt16 maps a []Big_Int to a []Int16.
func (MapBig_Int) ToInt16(aa []big.Int, mapFn func(big.Int) int16) []int16 {
	bb := []int16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt32 maps a []Big_Int to a []Int32.
func (MapBig_Int) ToInt32(aa []big.Int, mapFn func(big.Int) int32) []int32 {
	bb := []int32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt64 maps a []Big_Int to a []Int64.
func (MapBig_Int) ToInt64(aa []big.Int, mapFn func(big.Int) int64) []int64 {
	bb := []int64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat32 maps a []Big_Int to a []Float32.
func (MapBig_Int) ToFloat32(aa []big.Int, mapFn func(big.Int) float32) []float32 {
	bb := []float32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat64 maps a []Big_Int to a []Float64.
func (MapBig_Int) ToFloat64(aa []big.Int, mapFn func(big.Int) float64) []float64 {
	bb := []float64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint maps a []Big_Int to a []Uint.
func (MapBig_Int) ToUint(aa []big.Int, mapFn func(big.Int) uint) []uint {
	bb := []uint{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint8 maps a []Big_Int to a []Uint8.
func (MapBig_Int) ToUint8(aa []big.Int, mapFn func(big.Int) uint8) []uint8 {
	bb := []uint8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint16 maps a []Big_Int to a []Uint16.
func (MapBig_Int) ToUint16(aa []big.Int, mapFn func(big.Int) uint16) []uint16 {
	bb := []uint16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint32 maps a []Big_Int to a []Uint32.
func (MapBig_Int) ToUint32(aa []big.Int, mapFn func(big.Int) uint32) []uint32 {
	bb := []uint32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint64 maps a []Big_Int to a []Uint64.
func (MapBig_Int) ToUint64(aa []big.Int, mapFn func(big.Int) uint64) []uint64 {
	bb := []uint64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex64 maps a []Big_Int to a []Complex64.
func (MapBig_Int) ToComplex64(aa []big.Int, mapFn func(big.Int) complex64) []complex64 {
	bb := []complex64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex128 maps a []Big_Int to a []Complex128.
func (MapBig_Int) ToComplex128(aa []big.Int, mapFn func(big.Int) complex128) []complex128 {
	bb := []complex128{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUintptr maps a []Big_Int to a []Uintptr.
func (MapBig_Int) ToUintptr(aa []big.Int, mapFn func(big.Int) uintptr) []uintptr {
	bb := []uintptr{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToError maps a []Big_Int to a []Error.
func (MapBig_Int) ToError(aa []big.Int, mapFn func(big.Int) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Int maps a []Big_Int to a []Big_Int.
func (MapBig_Int) ToBig_Int(aa []big.Int, mapFn func(big.Int) big.Int) []big.Int {
	bb := []big.Int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Float maps a []Big_Int to a []Big_Float.
func (MapBig_Int) ToBig_Float(aa []big.Int, mapFn func(big.Int) big.Float) []big.Float {
	bb := []big.Float{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Rat maps a []Big_Int to a []Big_Rat.
func (MapBig_Int) ToBig_Rat(aa []big.Int, mapFn func(big.Int) big.Rat) []big.Rat {
	bb := []big.Rat{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
