// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xint64

// Do executes the test against a []Int64.
func (AllInt64) Do(aa []int64, test func(int64) bool) bool {
	for _, a := range aa {
		if !test(a) {
			return false
		}
	}
	return true
}
