// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xint64

// MapInt64 contains methods for applying Map tranforms between Int64s and other types.
type MapInt64 struct{}

// Map provides access to MapInt64 methods.
var Map MapInt64
