// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xint64

// ToError maps a []Int64 to a []Error.
func (MapInt64) ToError(aa []int64, mapFn func(int64) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
