// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xint64

// ToBool maps a []Int64 to a []Bool.
func (MapInt64) ToBool(aa []int64, mapFn func(int64) bool) []bool {
	bb := []bool{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToByte maps a []Int64 to a []Byte.
func (MapInt64) ToByte(aa []int64, mapFn func(int64) byte) []byte {
	bb := []byte{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex128 maps a []Int64 to a []Complex128.
func (MapInt64) ToComplex128(aa []int64, mapFn func(int64) complex128) []complex128 {
	bb := []complex128{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex64 maps a []Int64 to a []Complex64.
func (MapInt64) ToComplex64(aa []int64, mapFn func(int64) complex64) []complex64 {
	bb := []complex64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToError maps a []Int64 to a []Error.
func (MapInt64) ToError(aa []int64, mapFn func(int64) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat32 maps a []Int64 to a []Float32.
func (MapInt64) ToFloat32(aa []int64, mapFn func(int64) float32) []float32 {
	bb := []float32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat64 maps a []Int64 to a []Float64.
func (MapInt64) ToFloat64(aa []int64, mapFn func(int64) float64) []float64 {
	bb := []float64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt maps a []Int64 to a []Int.
func (MapInt64) ToInt(aa []int64, mapFn func(int64) int) []int {
	bb := []int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt16 maps a []Int64 to a []Int16.
func (MapInt64) ToInt16(aa []int64, mapFn func(int64) int16) []int16 {
	bb := []int16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt32 maps a []Int64 to a []Int32.
func (MapInt64) ToInt32(aa []int64, mapFn func(int64) int32) []int32 {
	bb := []int32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt64 maps a []Int64 to a []Int64.
func (MapInt64) ToInt64(aa []int64, mapFn func(int64) int64) []int64 {
	bb := []int64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt8 maps a []Int64 to a []Int8.
func (MapInt64) ToInt8(aa []int64, mapFn func(int64) int8) []int8 {
	bb := []int8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToRune maps a []Int64 to a []Rune.
func (MapInt64) ToRune(aa []int64, mapFn func(int64) rune) []rune {
	bb := []rune{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToString maps a []Int64 to a []String.
func (MapInt64) ToString(aa []int64, mapFn func(int64) string) []string {
	bb := []string{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint maps a []Int64 to a []Uint.
func (MapInt64) ToUint(aa []int64, mapFn func(int64) uint) []uint {
	bb := []uint{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint16 maps a []Int64 to a []Uint16.
func (MapInt64) ToUint16(aa []int64, mapFn func(int64) uint16) []uint16 {
	bb := []uint16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint32 maps a []Int64 to a []Uint32.
func (MapInt64) ToUint32(aa []int64, mapFn func(int64) uint32) []uint32 {
	bb := []uint32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint64 maps a []Int64 to a []Uint64.
func (MapInt64) ToUint64(aa []int64, mapFn func(int64) uint64) []uint64 {
	bb := []uint64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint8 maps a []Int64 to a []Uint8.
func (MapInt64) ToUint8(aa []int64, mapFn func(int64) uint8) []uint8 {
	bb := []uint8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUintptr maps a []Int64 to a []Uintptr.
func (MapInt64) ToUintptr(aa []int64, mapFn func(int64) uintptr) []uintptr {
	bb := []uintptr{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
