// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xint

// MapInt contains methods for applying Map tranforms between Ints and other types.
type MapInt struct{}

// Map provides access to MapInt methods.
var Map MapInt
