// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuint16

// Do executes the test against a []Uint16.
func (AllUint16) Do(aa []uint16, test func(uint16) bool) bool {
	for _, a := range aa {
		if !test(a) {
			return false
		}
	}
	return true
}
