// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuint16

// ToError maps a []Uint16 to a []Error.
func (MapUint16) ToError(aa []uint16, mapFn func(uint16) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
