// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuint16

import "math/big"

// ToBool maps a []Uint16 to a []Bool.
func (MapUint16) ToBool(aa []uint16, mapFn func(uint16) bool) []bool {
	bb := []bool{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToRune maps a []Uint16 to a []Rune.
func (MapUint16) ToRune(aa []uint16, mapFn func(uint16) rune) []rune {
	bb := []rune{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToByte maps a []Uint16 to a []Byte.
func (MapUint16) ToByte(aa []uint16, mapFn func(uint16) byte) []byte {
	bb := []byte{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToString maps a []Uint16 to a []String.
func (MapUint16) ToString(aa []uint16, mapFn func(uint16) string) []string {
	bb := []string{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt maps a []Uint16 to a []Int.
func (MapUint16) ToInt(aa []uint16, mapFn func(uint16) int) []int {
	bb := []int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt8 maps a []Uint16 to a []Int8.
func (MapUint16) ToInt8(aa []uint16, mapFn func(uint16) int8) []int8 {
	bb := []int8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt16 maps a []Uint16 to a []Int16.
func (MapUint16) ToInt16(aa []uint16, mapFn func(uint16) int16) []int16 {
	bb := []int16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt32 maps a []Uint16 to a []Int32.
func (MapUint16) ToInt32(aa []uint16, mapFn func(uint16) int32) []int32 {
	bb := []int32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt64 maps a []Uint16 to a []Int64.
func (MapUint16) ToInt64(aa []uint16, mapFn func(uint16) int64) []int64 {
	bb := []int64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat32 maps a []Uint16 to a []Float32.
func (MapUint16) ToFloat32(aa []uint16, mapFn func(uint16) float32) []float32 {
	bb := []float32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat64 maps a []Uint16 to a []Float64.
func (MapUint16) ToFloat64(aa []uint16, mapFn func(uint16) float64) []float64 {
	bb := []float64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint maps a []Uint16 to a []Uint.
func (MapUint16) ToUint(aa []uint16, mapFn func(uint16) uint) []uint {
	bb := []uint{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint8 maps a []Uint16 to a []Uint8.
func (MapUint16) ToUint8(aa []uint16, mapFn func(uint16) uint8) []uint8 {
	bb := []uint8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint16 maps a []Uint16 to a []Uint16.
func (MapUint16) ToUint16(aa []uint16, mapFn func(uint16) uint16) []uint16 {
	bb := []uint16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint32 maps a []Uint16 to a []Uint32.
func (MapUint16) ToUint32(aa []uint16, mapFn func(uint16) uint32) []uint32 {
	bb := []uint32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint64 maps a []Uint16 to a []Uint64.
func (MapUint16) ToUint64(aa []uint16, mapFn func(uint16) uint64) []uint64 {
	bb := []uint64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex64 maps a []Uint16 to a []Complex64.
func (MapUint16) ToComplex64(aa []uint16, mapFn func(uint16) complex64) []complex64 {
	bb := []complex64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex128 maps a []Uint16 to a []Complex128.
func (MapUint16) ToComplex128(aa []uint16, mapFn func(uint16) complex128) []complex128 {
	bb := []complex128{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUintptr maps a []Uint16 to a []Uintptr.
func (MapUint16) ToUintptr(aa []uint16, mapFn func(uint16) uintptr) []uintptr {
	bb := []uintptr{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToError maps a []Uint16 to a []Error.
func (MapUint16) ToError(aa []uint16, mapFn func(uint16) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Int maps a []Uint16 to a []Big_Int.
func (MapUint16) ToBig_Int(aa []uint16, mapFn func(uint16) big.Int) []big.Int {
	bb := []big.Int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Float maps a []Uint16 to a []Big_Float.
func (MapUint16) ToBig_Float(aa []uint16, mapFn func(uint16) big.Float) []big.Float {
	bb := []big.Float{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Rat maps a []Uint16 to a []Big_Rat.
func (MapUint16) ToBig_Rat(aa []uint16, mapFn func(uint16) big.Rat) []big.Rat {
	bb := []big.Rat{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
