// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuint16

// MapUint16 contains methods for applying Map tranforms between Uint16s and other types.
type MapUint16 struct{}

// Map provides access to MapUint16 methods.
var Map MapUint16
