// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuint32

// Do executes the test against a []Uint32.
func (AllUint32) Do(aa []uint32, test func(uint32) bool) bool {
	for _, a := range aa {
		if !test(a) {
			return false
		}
	}
	return true
}
