// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuint32

// MapUint32 contains methods for applying Map tranforms between Uint32s and other types.
type MapUint32 struct{}

// Map provides access to MapUint32 methods.
var Map MapUint32
