// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xint16

// Do executes the test against a []Int16.
func (AllInt16) Do(aa []int16, test func(int16) bool) bool {
	for _, a := range aa {
		if !test(a) {
			return false
		}
	}
	return true
}
