// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xint16

// ToError maps a []Int16 to a []Error.
func (MapInt16) ToError(aa []int16, mapFn func(int16) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
