// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xint16

// MapInt16 contains methods for applying Map tranforms between Int16s and other types.
type MapInt16 struct{}

// Map provides access to MapInt16 methods.
var Map MapInt16
