// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xfloat32

// Do executes the test against a []Float32.
func (AllFloat32) Do(aa []float32, test func(float32) bool) bool {
	for _, a := range aa {
		if !test(a) {
			return false
		}
	}
	return true
}
