// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xfloat32

// ToError maps a []Float32 to a []Error.
func (MapFloat32) ToError(aa []float32, mapFn func(float32) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
