// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xfloat32

// ToBool maps a []Float32 to a []Bool.
func (MapFloat32) ToBool(aa []float32, mapFn func(float32) bool) []bool {
	bb := []bool{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToByte maps a []Float32 to a []Byte.
func (MapFloat32) ToByte(aa []float32, mapFn func(float32) byte) []byte {
	bb := []byte{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex128 maps a []Float32 to a []Complex128.
func (MapFloat32) ToComplex128(aa []float32, mapFn func(float32) complex128) []complex128 {
	bb := []complex128{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex64 maps a []Float32 to a []Complex64.
func (MapFloat32) ToComplex64(aa []float32, mapFn func(float32) complex64) []complex64 {
	bb := []complex64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToError maps a []Float32 to a []Error.
func (MapFloat32) ToError(aa []float32, mapFn func(float32) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat32 maps a []Float32 to a []Float32.
func (MapFloat32) ToFloat32(aa []float32, mapFn func(float32) float32) []float32 {
	bb := []float32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat64 maps a []Float32 to a []Float64.
func (MapFloat32) ToFloat64(aa []float32, mapFn func(float32) float64) []float64 {
	bb := []float64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt maps a []Float32 to a []Int.
func (MapFloat32) ToInt(aa []float32, mapFn func(float32) int) []int {
	bb := []int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt16 maps a []Float32 to a []Int16.
func (MapFloat32) ToInt16(aa []float32, mapFn func(float32) int16) []int16 {
	bb := []int16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt32 maps a []Float32 to a []Int32.
func (MapFloat32) ToInt32(aa []float32, mapFn func(float32) int32) []int32 {
	bb := []int32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt64 maps a []Float32 to a []Int64.
func (MapFloat32) ToInt64(aa []float32, mapFn func(float32) int64) []int64 {
	bb := []int64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt8 maps a []Float32 to a []Int8.
func (MapFloat32) ToInt8(aa []float32, mapFn func(float32) int8) []int8 {
	bb := []int8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToRune maps a []Float32 to a []Rune.
func (MapFloat32) ToRune(aa []float32, mapFn func(float32) rune) []rune {
	bb := []rune{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToString maps a []Float32 to a []String.
func (MapFloat32) ToString(aa []float32, mapFn func(float32) string) []string {
	bb := []string{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint maps a []Float32 to a []Uint.
func (MapFloat32) ToUint(aa []float32, mapFn func(float32) uint) []uint {
	bb := []uint{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint16 maps a []Float32 to a []Uint16.
func (MapFloat32) ToUint16(aa []float32, mapFn func(float32) uint16) []uint16 {
	bb := []uint16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint32 maps a []Float32 to a []Uint32.
func (MapFloat32) ToUint32(aa []float32, mapFn func(float32) uint32) []uint32 {
	bb := []uint32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint64 maps a []Float32 to a []Uint64.
func (MapFloat32) ToUint64(aa []float32, mapFn func(float32) uint64) []uint64 {
	bb := []uint64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint8 maps a []Float32 to a []Uint8.
func (MapFloat32) ToUint8(aa []float32, mapFn func(float32) uint8) []uint8 {
	bb := []uint8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUintptr maps a []Float32 to a []Uintptr.
func (MapFloat32) ToUintptr(aa []float32, mapFn func(float32) uintptr) []uintptr {
	bb := []uintptr{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
