// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xfloat32

// MapFloat32 contains methods for applying Map tranforms between Float32s and other types.
type MapFloat32 struct{}

// Map provides access to MapFloat32 methods.
var Map MapFloat32
