// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xrune

// Do executes the test against a []Rune.
func (AllRune) Do(aa []rune, test func(rune) bool) bool {
	for _, a := range aa {
		if !test(a) {
			return false
		}
	}
	return true
}
