// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xrune

// MapRune contains methods for applying Map tranforms between Runes and other types.
type MapRune struct{}

// Map provides access to MapRune methods.
var Map MapRune
