// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xrune

// ToError maps a []Rune to a []Error.
func (MapRune) ToError(aa []rune, mapFn func(rune) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
