// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xcomplex128

// Do executes the test against a []Complex128.
func (AllComplex128) Do(aa []complex128, test func(complex128) bool) bool {
	for _, a := range aa {
		if !test(a) {
			return false
		}
	}
	return true
}
