// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xcomplex128

// MapComplex128 contains methods for applying Map tranforms between Complex128s and other types.
type MapComplex128 struct{}

// Map provides access to MapComplex128 methods.
var Map MapComplex128
