// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xcomplex128

// ToError maps a []Complex128 to a []Error.
func (MapComplex128) ToError(aa []complex128, mapFn func(complex128) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
