// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xcomplex128

// ToBool maps a []Complex128 to a []Bool.
func (MapComplex128) ToBool(aa []complex128, mapFn func(complex128) bool) []bool {
	bb := []bool{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToByte maps a []Complex128 to a []Byte.
func (MapComplex128) ToByte(aa []complex128, mapFn func(complex128) byte) []byte {
	bb := []byte{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex128 maps a []Complex128 to a []Complex128.
func (MapComplex128) ToComplex128(aa []complex128, mapFn func(complex128) complex128) []complex128 {
	bb := []complex128{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex64 maps a []Complex128 to a []Complex64.
func (MapComplex128) ToComplex64(aa []complex128, mapFn func(complex128) complex64) []complex64 {
	bb := []complex64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToError maps a []Complex128 to a []Error.
func (MapComplex128) ToError(aa []complex128, mapFn func(complex128) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat32 maps a []Complex128 to a []Float32.
func (MapComplex128) ToFloat32(aa []complex128, mapFn func(complex128) float32) []float32 {
	bb := []float32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat64 maps a []Complex128 to a []Float64.
func (MapComplex128) ToFloat64(aa []complex128, mapFn func(complex128) float64) []float64 {
	bb := []float64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt maps a []Complex128 to a []Int.
func (MapComplex128) ToInt(aa []complex128, mapFn func(complex128) int) []int {
	bb := []int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt16 maps a []Complex128 to a []Int16.
func (MapComplex128) ToInt16(aa []complex128, mapFn func(complex128) int16) []int16 {
	bb := []int16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt32 maps a []Complex128 to a []Int32.
func (MapComplex128) ToInt32(aa []complex128, mapFn func(complex128) int32) []int32 {
	bb := []int32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt64 maps a []Complex128 to a []Int64.
func (MapComplex128) ToInt64(aa []complex128, mapFn func(complex128) int64) []int64 {
	bb := []int64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt8 maps a []Complex128 to a []Int8.
func (MapComplex128) ToInt8(aa []complex128, mapFn func(complex128) int8) []int8 {
	bb := []int8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToRune maps a []Complex128 to a []Rune.
func (MapComplex128) ToRune(aa []complex128, mapFn func(complex128) rune) []rune {
	bb := []rune{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToString maps a []Complex128 to a []String.
func (MapComplex128) ToString(aa []complex128, mapFn func(complex128) string) []string {
	bb := []string{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint maps a []Complex128 to a []Uint.
func (MapComplex128) ToUint(aa []complex128, mapFn func(complex128) uint) []uint {
	bb := []uint{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint16 maps a []Complex128 to a []Uint16.
func (MapComplex128) ToUint16(aa []complex128, mapFn func(complex128) uint16) []uint16 {
	bb := []uint16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint32 maps a []Complex128 to a []Uint32.
func (MapComplex128) ToUint32(aa []complex128, mapFn func(complex128) uint32) []uint32 {
	bb := []uint32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint64 maps a []Complex128 to a []Uint64.
func (MapComplex128) ToUint64(aa []complex128, mapFn func(complex128) uint64) []uint64 {
	bb := []uint64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint8 maps a []Complex128 to a []Uint8.
func (MapComplex128) ToUint8(aa []complex128, mapFn func(complex128) uint8) []uint8 {
	bb := []uint8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUintptr maps a []Complex128 to a []Uintptr.
func (MapComplex128) ToUintptr(aa []complex128, mapFn func(complex128) uintptr) []uintptr {
	bb := []uintptr{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
