// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuint8

// AllUint8 contains methods for applying an All trasnform to various types.
type AllUint8 struct{}

// All applies a test function to each element in the slice, and returns true if
// the test function returns true for all items in the slice.
var All AllUint8
