// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuint8

// MapUint8 contains methods for applying Map tranforms between Uint8s and other types.
type MapUint8 struct{}

// Map provides access to MapUint8 methods.
var Map MapUint8
