// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuint8

// ToError maps a []Uint8 to a []Error.
func (MapUint8) ToError(aa []uint8, mapFn func(uint8) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
