// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuint

// MapUint contains methods for applying Map tranforms between Uints and other types.
type MapUint struct{}

// Map provides access to MapUint methods.
var Map MapUint
