// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuint

import "math/big"

// ToBool maps a []Uint to a []Bool.
func (MapUint) ToBool(aa []uint, mapFn func(uint) bool) []bool {
	bb := []bool{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToRune maps a []Uint to a []Rune.
func (MapUint) ToRune(aa []uint, mapFn func(uint) rune) []rune {
	bb := []rune{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToByte maps a []Uint to a []Byte.
func (MapUint) ToByte(aa []uint, mapFn func(uint) byte) []byte {
	bb := []byte{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToString maps a []Uint to a []String.
func (MapUint) ToString(aa []uint, mapFn func(uint) string) []string {
	bb := []string{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt maps a []Uint to a []Int.
func (MapUint) ToInt(aa []uint, mapFn func(uint) int) []int {
	bb := []int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt8 maps a []Uint to a []Int8.
func (MapUint) ToInt8(aa []uint, mapFn func(uint) int8) []int8 {
	bb := []int8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt16 maps a []Uint to a []Int16.
func (MapUint) ToInt16(aa []uint, mapFn func(uint) int16) []int16 {
	bb := []int16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt32 maps a []Uint to a []Int32.
func (MapUint) ToInt32(aa []uint, mapFn func(uint) int32) []int32 {
	bb := []int32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt64 maps a []Uint to a []Int64.
func (MapUint) ToInt64(aa []uint, mapFn func(uint) int64) []int64 {
	bb := []int64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat32 maps a []Uint to a []Float32.
func (MapUint) ToFloat32(aa []uint, mapFn func(uint) float32) []float32 {
	bb := []float32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat64 maps a []Uint to a []Float64.
func (MapUint) ToFloat64(aa []uint, mapFn func(uint) float64) []float64 {
	bb := []float64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint maps a []Uint to a []Uint.
func (MapUint) ToUint(aa []uint, mapFn func(uint) uint) []uint {
	bb := []uint{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint8 maps a []Uint to a []Uint8.
func (MapUint) ToUint8(aa []uint, mapFn func(uint) uint8) []uint8 {
	bb := []uint8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint16 maps a []Uint to a []Uint16.
func (MapUint) ToUint16(aa []uint, mapFn func(uint) uint16) []uint16 {
	bb := []uint16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint32 maps a []Uint to a []Uint32.
func (MapUint) ToUint32(aa []uint, mapFn func(uint) uint32) []uint32 {
	bb := []uint32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint64 maps a []Uint to a []Uint64.
func (MapUint) ToUint64(aa []uint, mapFn func(uint) uint64) []uint64 {
	bb := []uint64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex64 maps a []Uint to a []Complex64.
func (MapUint) ToComplex64(aa []uint, mapFn func(uint) complex64) []complex64 {
	bb := []complex64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex128 maps a []Uint to a []Complex128.
func (MapUint) ToComplex128(aa []uint, mapFn func(uint) complex128) []complex128 {
	bb := []complex128{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUintptr maps a []Uint to a []Uintptr.
func (MapUint) ToUintptr(aa []uint, mapFn func(uint) uintptr) []uintptr {
	bb := []uintptr{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToError maps a []Uint to a []Error.
func (MapUint) ToError(aa []uint, mapFn func(uint) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Int maps a []Uint to a []Big_Int.
func (MapUint) ToBig_Int(aa []uint, mapFn func(uint) big.Int) []big.Int {
	bb := []big.Int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Float maps a []Uint to a []Big_Float.
func (MapUint) ToBig_Float(aa []uint, mapFn func(uint) big.Float) []big.Float {
	bb := []big.Float{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Rat maps a []Uint to a []Big_Rat.
func (MapUint) ToBig_Rat(aa []uint, mapFn func(uint) big.Rat) []big.Rat {
	bb := []big.Rat{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
