// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xfloat64

// Do executes the test against a []Float64.
func (AllFloat64) Do(aa []float64, test func(float64) bool) bool {
	for _, a := range aa {
		if !test(a) {
			return false
		}
	}
	return true
}
