// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xfloat64

// ToError maps a []Float64 to a []Error.
func (MapFloat64) ToError(aa []float64, mapFn func(float64) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
