// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xfloat64

// MapFloat64 contains methods for applying Map tranforms between Float64s and other types.
type MapFloat64 struct{}

// Map provides access to MapFloat64 methods.
var Map MapFloat64
