// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xint32

// Do executes the test against a []Int32.
func (AllInt32) Do(aa []int32, test func(int32) bool) bool {
	for _, a := range aa {
		if !test(a) {
			return false
		}
	}
	return true
}
