// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xint32

// Map contains map functions.
type Map struct{}

// ToString maps a []Int32 to a []String.
func (Map) ToString(aa []int32, mapFn func(int32) string) []string {
	bb := []string{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
