// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xint32

// MapInt32 contains methods for applying Map tranforms between Int32s and other types.
type MapInt32 struct{}

// Map provides access to MapInt32 methods.
var Map MapInt32
