// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xint32

// ToError maps a []Int32 to a []Error.
func (MapInt32) ToError(aa []int32, mapFn func(int32) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
