// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xcomplex64

// MapComplex64 contains methods for applying Map tranforms between Complex64s and other types.
type MapComplex64 struct{}

// Map provides access to MapComplex64 methods.
var Map MapComplex64
