// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xstring

import "math/big"

// ToBool maps a []String to a []Bool.
func (MapString) ToBool(aa []string, mapFn func(string) bool) []bool {
	bb := []bool{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToRune maps a []String to a []Rune.
func (MapString) ToRune(aa []string, mapFn func(string) rune) []rune {
	bb := []rune{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToByte maps a []String to a []Byte.
func (MapString) ToByte(aa []string, mapFn func(string) byte) []byte {
	bb := []byte{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToString maps a []String to a []String.
func (MapString) ToString(aa []string, mapFn func(string) string) []string {
	bb := []string{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt maps a []String to a []Int.
func (MapString) ToInt(aa []string, mapFn func(string) int) []int {
	bb := []int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt8 maps a []String to a []Int8.
func (MapString) ToInt8(aa []string, mapFn func(string) int8) []int8 {
	bb := []int8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt16 maps a []String to a []Int16.
func (MapString) ToInt16(aa []string, mapFn func(string) int16) []int16 {
	bb := []int16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt32 maps a []String to a []Int32.
func (MapString) ToInt32(aa []string, mapFn func(string) int32) []int32 {
	bb := []int32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt64 maps a []String to a []Int64.
func (MapString) ToInt64(aa []string, mapFn func(string) int64) []int64 {
	bb := []int64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat32 maps a []String to a []Float32.
func (MapString) ToFloat32(aa []string, mapFn func(string) float32) []float32 {
	bb := []float32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat64 maps a []String to a []Float64.
func (MapString) ToFloat64(aa []string, mapFn func(string) float64) []float64 {
	bb := []float64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint maps a []String to a []Uint.
func (MapString) ToUint(aa []string, mapFn func(string) uint) []uint {
	bb := []uint{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint8 maps a []String to a []Uint8.
func (MapString) ToUint8(aa []string, mapFn func(string) uint8) []uint8 {
	bb := []uint8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint16 maps a []String to a []Uint16.
func (MapString) ToUint16(aa []string, mapFn func(string) uint16) []uint16 {
	bb := []uint16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint32 maps a []String to a []Uint32.
func (MapString) ToUint32(aa []string, mapFn func(string) uint32) []uint32 {
	bb := []uint32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint64 maps a []String to a []Uint64.
func (MapString) ToUint64(aa []string, mapFn func(string) uint64) []uint64 {
	bb := []uint64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex64 maps a []String to a []Complex64.
func (MapString) ToComplex64(aa []string, mapFn func(string) complex64) []complex64 {
	bb := []complex64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex128 maps a []String to a []Complex128.
func (MapString) ToComplex128(aa []string, mapFn func(string) complex128) []complex128 {
	bb := []complex128{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUintptr maps a []String to a []Uintptr.
func (MapString) ToUintptr(aa []string, mapFn func(string) uintptr) []uintptr {
	bb := []uintptr{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToError maps a []String to a []Error.
func (MapString) ToError(aa []string, mapFn func(string) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Int maps a []String to a []Big_Int.
func (MapString) ToBig_Int(aa []string, mapFn func(string) big.Int) []big.Int {
	bb := []big.Int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Float maps a []String to a []Big_Float.
func (MapString) ToBig_Float(aa []string, mapFn func(string) big.Float) []big.Float {
	bb := []big.Float{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Rat maps a []String to a []Big_Rat.
func (MapString) ToBig_Rat(aa []string, mapFn func(string) big.Rat) []big.Rat {
	bb := []big.Rat{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
