// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xstring

// MapString contains methods for applying Map tranforms between Strings and other types.
type MapString struct{}

// Map provides access to MapString methods.
var Map MapString
