// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xstring

// MapString contains methods for applying Map tranforms to various types.
type MapString struct{}

// Map contains map functions.
var Map MapString
