// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuintptr

// Do executes the test against a []Uintptr.
func (AllUintptr) Do(aa []uintptr, test func(uintptr) bool) bool {
	for _, a := range aa {
		if !test(a) {
			return false
		}
	}
	return true
}
