// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuintptr

// MapUintptr contains methods for applying Map tranforms between Uintptrs and other types.
type MapUintptr struct{}

// Map provides access to MapUintptr methods.
var Map MapUintptr
