// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuintptr

import "math/big"

// ToBool maps a []Uintptr to a []Bool.
func (MapUintptr) ToBool(aa []uintptr, mapFn func(uintptr) bool) []bool {
	bb := []bool{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToRune maps a []Uintptr to a []Rune.
func (MapUintptr) ToRune(aa []uintptr, mapFn func(uintptr) rune) []rune {
	bb := []rune{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToByte maps a []Uintptr to a []Byte.
func (MapUintptr) ToByte(aa []uintptr, mapFn func(uintptr) byte) []byte {
	bb := []byte{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToString maps a []Uintptr to a []String.
func (MapUintptr) ToString(aa []uintptr, mapFn func(uintptr) string) []string {
	bb := []string{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt maps a []Uintptr to a []Int.
func (MapUintptr) ToInt(aa []uintptr, mapFn func(uintptr) int) []int {
	bb := []int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt8 maps a []Uintptr to a []Int8.
func (MapUintptr) ToInt8(aa []uintptr, mapFn func(uintptr) int8) []int8 {
	bb := []int8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt16 maps a []Uintptr to a []Int16.
func (MapUintptr) ToInt16(aa []uintptr, mapFn func(uintptr) int16) []int16 {
	bb := []int16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt32 maps a []Uintptr to a []Int32.
func (MapUintptr) ToInt32(aa []uintptr, mapFn func(uintptr) int32) []int32 {
	bb := []int32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt64 maps a []Uintptr to a []Int64.
func (MapUintptr) ToInt64(aa []uintptr, mapFn func(uintptr) int64) []int64 {
	bb := []int64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat32 maps a []Uintptr to a []Float32.
func (MapUintptr) ToFloat32(aa []uintptr, mapFn func(uintptr) float32) []float32 {
	bb := []float32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat64 maps a []Uintptr to a []Float64.
func (MapUintptr) ToFloat64(aa []uintptr, mapFn func(uintptr) float64) []float64 {
	bb := []float64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint maps a []Uintptr to a []Uint.
func (MapUintptr) ToUint(aa []uintptr, mapFn func(uintptr) uint) []uint {
	bb := []uint{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint8 maps a []Uintptr to a []Uint8.
func (MapUintptr) ToUint8(aa []uintptr, mapFn func(uintptr) uint8) []uint8 {
	bb := []uint8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint16 maps a []Uintptr to a []Uint16.
func (MapUintptr) ToUint16(aa []uintptr, mapFn func(uintptr) uint16) []uint16 {
	bb := []uint16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint32 maps a []Uintptr to a []Uint32.
func (MapUintptr) ToUint32(aa []uintptr, mapFn func(uintptr) uint32) []uint32 {
	bb := []uint32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint64 maps a []Uintptr to a []Uint64.
func (MapUintptr) ToUint64(aa []uintptr, mapFn func(uintptr) uint64) []uint64 {
	bb := []uint64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex64 maps a []Uintptr to a []Complex64.
func (MapUintptr) ToComplex64(aa []uintptr, mapFn func(uintptr) complex64) []complex64 {
	bb := []complex64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex128 maps a []Uintptr to a []Complex128.
func (MapUintptr) ToComplex128(aa []uintptr, mapFn func(uintptr) complex128) []complex128 {
	bb := []complex128{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUintptr maps a []Uintptr to a []Uintptr.
func (MapUintptr) ToUintptr(aa []uintptr, mapFn func(uintptr) uintptr) []uintptr {
	bb := []uintptr{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToError maps a []Uintptr to a []Error.
func (MapUintptr) ToError(aa []uintptr, mapFn func(uintptr) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Int maps a []Uintptr to a []Big_Int.
func (MapUintptr) ToBig_Int(aa []uintptr, mapFn func(uintptr) big.Int) []big.Int {
	bb := []big.Int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Float maps a []Uintptr to a []Big_Float.
func (MapUintptr) ToBig_Float(aa []uintptr, mapFn func(uintptr) big.Float) []big.Float {
	bb := []big.Float{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Rat maps a []Uintptr to a []Big_Rat.
func (MapUintptr) ToBig_Rat(aa []uintptr, mapFn func(uintptr) big.Rat) []big.Rat {
	bb := []big.Rat{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
