// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuintptr

// ToError maps a []Uintptr to a []Error.
func (MapUintptr) ToError(aa []uintptr, mapFn func(uintptr) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
