// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xbool

// Do executes the test against a []Bool.
func (AllBool) Do(aa []bool, test func(bool) bool) bool {
	for _, a := range aa {
		if !test(a) {
			return false
		}
	}
	return true
}
