// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xbool

// MapBool contains methods for applying Map tranforms between Bools and other types.
type MapBool struct{}

// Map provides access to MapBool methods.
var Map MapBool
