// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xbool

// ToBool maps a []Bool to a []Bool.
func (MapBool) ToBool(aa []bool, mapFn func(bool) bool) []bool {
	bb := []bool{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToByte maps a []Bool to a []Byte.
func (MapBool) ToByte(aa []bool, mapFn func(bool) byte) []byte {
	bb := []byte{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex128 maps a []Bool to a []Complex128.
func (MapBool) ToComplex128(aa []bool, mapFn func(bool) complex128) []complex128 {
	bb := []complex128{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex64 maps a []Bool to a []Complex64.
func (MapBool) ToComplex64(aa []bool, mapFn func(bool) complex64) []complex64 {
	bb := []complex64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToError maps a []Bool to a []Error.
func (MapBool) ToError(aa []bool, mapFn func(bool) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat32 maps a []Bool to a []Float32.
func (MapBool) ToFloat32(aa []bool, mapFn func(bool) float32) []float32 {
	bb := []float32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat64 maps a []Bool to a []Float64.
func (MapBool) ToFloat64(aa []bool, mapFn func(bool) float64) []float64 {
	bb := []float64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt maps a []Bool to a []Int.
func (MapBool) ToInt(aa []bool, mapFn func(bool) int) []int {
	bb := []int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt16 maps a []Bool to a []Int16.
func (MapBool) ToInt16(aa []bool, mapFn func(bool) int16) []int16 {
	bb := []int16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt32 maps a []Bool to a []Int32.
func (MapBool) ToInt32(aa []bool, mapFn func(bool) int32) []int32 {
	bb := []int32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt64 maps a []Bool to a []Int64.
func (MapBool) ToInt64(aa []bool, mapFn func(bool) int64) []int64 {
	bb := []int64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt8 maps a []Bool to a []Int8.
func (MapBool) ToInt8(aa []bool, mapFn func(bool) int8) []int8 {
	bb := []int8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToRune maps a []Bool to a []Rune.
func (MapBool) ToRune(aa []bool, mapFn func(bool) rune) []rune {
	bb := []rune{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToString maps a []Bool to a []String.
func (MapBool) ToString(aa []bool, mapFn func(bool) string) []string {
	bb := []string{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint maps a []Bool to a []Uint.
func (MapBool) ToUint(aa []bool, mapFn func(bool) uint) []uint {
	bb := []uint{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint16 maps a []Bool to a []Uint16.
func (MapBool) ToUint16(aa []bool, mapFn func(bool) uint16) []uint16 {
	bb := []uint16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint32 maps a []Bool to a []Uint32.
func (MapBool) ToUint32(aa []bool, mapFn func(bool) uint32) []uint32 {
	bb := []uint32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint64 maps a []Bool to a []Uint64.
func (MapBool) ToUint64(aa []bool, mapFn func(bool) uint64) []uint64 {
	bb := []uint64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint8 maps a []Bool to a []Uint8.
func (MapBool) ToUint8(aa []bool, mapFn func(bool) uint8) []uint8 {
	bb := []uint8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUintptr maps a []Bool to a []Uintptr.
func (MapBool) ToUintptr(aa []bool, mapFn func(bool) uintptr) []uintptr {
	bb := []uintptr{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
