// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xerror

// Do executes the test against a []Error.
func (AllError) Do(aa []error, test func(error) bool) bool {
	for _, a := range aa {
		if !test(a) {
			return false
		}
	}
	return true
}
