// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xerror

// MapError contains methods for applying Map tranforms between Errors and other types.
type MapError struct{}

// Map provides access to MapError methods.
var Map MapError
