// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuint64

// Do executes the test against a []Uint64.
func (AllUint64) Do(aa []uint64, test func(uint64) bool) bool {
	for _, a := range aa {
		if !test(a) {
			return false
		}
	}
	return true
}
