// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuint64

// ToError maps a []Uint64 to a []Error.
func (MapUint64) ToError(aa []uint64, mapFn func(uint64) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
