// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuint64

// MapUint64 contains methods for applying Map tranforms between Uint64s and other types.
type MapUint64 struct{}

// Map provides access to MapUint64 methods.
var Map MapUint64
