// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xuint64

// ToBool maps a []Uint64 to a []Bool.
func (MapUint64) ToBool(aa []uint64, mapFn func(uint64) bool) []bool {
	bb := []bool{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToByte maps a []Uint64 to a []Byte.
func (MapUint64) ToByte(aa []uint64, mapFn func(uint64) byte) []byte {
	bb := []byte{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex128 maps a []Uint64 to a []Complex128.
func (MapUint64) ToComplex128(aa []uint64, mapFn func(uint64) complex128) []complex128 {
	bb := []complex128{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex64 maps a []Uint64 to a []Complex64.
func (MapUint64) ToComplex64(aa []uint64, mapFn func(uint64) complex64) []complex64 {
	bb := []complex64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToError maps a []Uint64 to a []Error.
func (MapUint64) ToError(aa []uint64, mapFn func(uint64) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat32 maps a []Uint64 to a []Float32.
func (MapUint64) ToFloat32(aa []uint64, mapFn func(uint64) float32) []float32 {
	bb := []float32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat64 maps a []Uint64 to a []Float64.
func (MapUint64) ToFloat64(aa []uint64, mapFn func(uint64) float64) []float64 {
	bb := []float64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt maps a []Uint64 to a []Int.
func (MapUint64) ToInt(aa []uint64, mapFn func(uint64) int) []int {
	bb := []int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt16 maps a []Uint64 to a []Int16.
func (MapUint64) ToInt16(aa []uint64, mapFn func(uint64) int16) []int16 {
	bb := []int16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt32 maps a []Uint64 to a []Int32.
func (MapUint64) ToInt32(aa []uint64, mapFn func(uint64) int32) []int32 {
	bb := []int32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt64 maps a []Uint64 to a []Int64.
func (MapUint64) ToInt64(aa []uint64, mapFn func(uint64) int64) []int64 {
	bb := []int64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt8 maps a []Uint64 to a []Int8.
func (MapUint64) ToInt8(aa []uint64, mapFn func(uint64) int8) []int8 {
	bb := []int8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToRune maps a []Uint64 to a []Rune.
func (MapUint64) ToRune(aa []uint64, mapFn func(uint64) rune) []rune {
	bb := []rune{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToString maps a []Uint64 to a []String.
func (MapUint64) ToString(aa []uint64, mapFn func(uint64) string) []string {
	bb := []string{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint maps a []Uint64 to a []Uint.
func (MapUint64) ToUint(aa []uint64, mapFn func(uint64) uint) []uint {
	bb := []uint{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint16 maps a []Uint64 to a []Uint16.
func (MapUint64) ToUint16(aa []uint64, mapFn func(uint64) uint16) []uint16 {
	bb := []uint16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint32 maps a []Uint64 to a []Uint32.
func (MapUint64) ToUint32(aa []uint64, mapFn func(uint64) uint32) []uint32 {
	bb := []uint32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint64 maps a []Uint64 to a []Uint64.
func (MapUint64) ToUint64(aa []uint64, mapFn func(uint64) uint64) []uint64 {
	bb := []uint64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint8 maps a []Uint64 to a []Uint8.
func (MapUint64) ToUint8(aa []uint64, mapFn func(uint64) uint8) []uint8 {
	bb := []uint8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUintptr maps a []Uint64 to a []Uintptr.
func (MapUint64) ToUintptr(aa []uint64, mapFn func(uint64) uintptr) []uintptr {
	bb := []uintptr{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
