// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xbigFloat

import "math/big"

// Do executes the test against a []Big_Float.
func (AllBig_Float) Do(aa []big.Float, test func(big.Float) bool) bool {
	for _, a := range aa {
		if !test(a) {
			return false
		}
	}
	return true
}
