// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xbigFloat

import "math/big"

// ToBool maps a []Big_Float to a []Bool.
func (MapBig_Float) ToBool(aa []big.Float, mapFn func(big.Float) bool) []bool {
	bb := []bool{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToRune maps a []Big_Float to a []Rune.
func (MapBig_Float) ToRune(aa []big.Float, mapFn func(big.Float) rune) []rune {
	bb := []rune{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToByte maps a []Big_Float to a []Byte.
func (MapBig_Float) ToByte(aa []big.Float, mapFn func(big.Float) byte) []byte {
	bb := []byte{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToString maps a []Big_Float to a []String.
func (MapBig_Float) ToString(aa []big.Float, mapFn func(big.Float) string) []string {
	bb := []string{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt maps a []Big_Float to a []Int.
func (MapBig_Float) ToInt(aa []big.Float, mapFn func(big.Float) int) []int {
	bb := []int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt8 maps a []Big_Float to a []Int8.
func (MapBig_Float) ToInt8(aa []big.Float, mapFn func(big.Float) int8) []int8 {
	bb := []int8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt16 maps a []Big_Float to a []Int16.
func (MapBig_Float) ToInt16(aa []big.Float, mapFn func(big.Float) int16) []int16 {
	bb := []int16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt32 maps a []Big_Float to a []Int32.
func (MapBig_Float) ToInt32(aa []big.Float, mapFn func(big.Float) int32) []int32 {
	bb := []int32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt64 maps a []Big_Float to a []Int64.
func (MapBig_Float) ToInt64(aa []big.Float, mapFn func(big.Float) int64) []int64 {
	bb := []int64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat32 maps a []Big_Float to a []Float32.
func (MapBig_Float) ToFloat32(aa []big.Float, mapFn func(big.Float) float32) []float32 {
	bb := []float32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat64 maps a []Big_Float to a []Float64.
func (MapBig_Float) ToFloat64(aa []big.Float, mapFn func(big.Float) float64) []float64 {
	bb := []float64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint maps a []Big_Float to a []Uint.
func (MapBig_Float) ToUint(aa []big.Float, mapFn func(big.Float) uint) []uint {
	bb := []uint{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint8 maps a []Big_Float to a []Uint8.
func (MapBig_Float) ToUint8(aa []big.Float, mapFn func(big.Float) uint8) []uint8 {
	bb := []uint8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint16 maps a []Big_Float to a []Uint16.
func (MapBig_Float) ToUint16(aa []big.Float, mapFn func(big.Float) uint16) []uint16 {
	bb := []uint16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint32 maps a []Big_Float to a []Uint32.
func (MapBig_Float) ToUint32(aa []big.Float, mapFn func(big.Float) uint32) []uint32 {
	bb := []uint32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint64 maps a []Big_Float to a []Uint64.
func (MapBig_Float) ToUint64(aa []big.Float, mapFn func(big.Float) uint64) []uint64 {
	bb := []uint64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex64 maps a []Big_Float to a []Complex64.
func (MapBig_Float) ToComplex64(aa []big.Float, mapFn func(big.Float) complex64) []complex64 {
	bb := []complex64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex128 maps a []Big_Float to a []Complex128.
func (MapBig_Float) ToComplex128(aa []big.Float, mapFn func(big.Float) complex128) []complex128 {
	bb := []complex128{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUintptr maps a []Big_Float to a []Uintptr.
func (MapBig_Float) ToUintptr(aa []big.Float, mapFn func(big.Float) uintptr) []uintptr {
	bb := []uintptr{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToError maps a []Big_Float to a []Error.
func (MapBig_Float) ToError(aa []big.Float, mapFn func(big.Float) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Int maps a []Big_Float to a []Big_Int.
func (MapBig_Float) ToBig_Int(aa []big.Float, mapFn func(big.Float) big.Int) []big.Int {
	bb := []big.Int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Float maps a []Big_Float to a []Big_Float.
func (MapBig_Float) ToBig_Float(aa []big.Float, mapFn func(big.Float) big.Float) []big.Float {
	bb := []big.Float{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToBig_Rat maps a []Big_Float to a []Big_Rat.
func (MapBig_Float) ToBig_Rat(aa []big.Float, mapFn func(big.Float) big.Rat) []big.Rat {
	bb := []big.Rat{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
