// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xbigFloat

// MapBig_Float contains methods for applying Map tranforms between Big_Floats and other types.
type MapBig_Float struct{}

// Map provides access to MapBig_Float methods.
var Map MapBig_Float
