// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xbyte

// Do executes the test against a []Byte.
func (AllByte) Do(aa []byte, test func(byte) bool) bool {
	for _, a := range aa {
		if !test(a) {
			return false
		}
	}
	return true
}
