// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xbyte

// MapByte contains methods for applying Map tranforms between Bytes and other types.
type MapByte struct{}

// Map provides access to MapByte methods.
var Map MapByte
