// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xbyte

// ToBool maps a []Byte to a []Bool.
func (MapByte) ToBool(aa []byte, mapFn func(byte) bool) []bool {
	bb := []bool{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToByte maps a []Byte to a []Byte.
func (MapByte) ToByte(aa []byte, mapFn func(byte) byte) []byte {
	bb := []byte{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex128 maps a []Byte to a []Complex128.
func (MapByte) ToComplex128(aa []byte, mapFn func(byte) complex128) []complex128 {
	bb := []complex128{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToComplex64 maps a []Byte to a []Complex64.
func (MapByte) ToComplex64(aa []byte, mapFn func(byte) complex64) []complex64 {
	bb := []complex64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToError maps a []Byte to a []Error.
func (MapByte) ToError(aa []byte, mapFn func(byte) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat32 maps a []Byte to a []Float32.
func (MapByte) ToFloat32(aa []byte, mapFn func(byte) float32) []float32 {
	bb := []float32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToFloat64 maps a []Byte to a []Float64.
func (MapByte) ToFloat64(aa []byte, mapFn func(byte) float64) []float64 {
	bb := []float64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt maps a []Byte to a []Int.
func (MapByte) ToInt(aa []byte, mapFn func(byte) int) []int {
	bb := []int{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt16 maps a []Byte to a []Int16.
func (MapByte) ToInt16(aa []byte, mapFn func(byte) int16) []int16 {
	bb := []int16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt32 maps a []Byte to a []Int32.
func (MapByte) ToInt32(aa []byte, mapFn func(byte) int32) []int32 {
	bb := []int32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt64 maps a []Byte to a []Int64.
func (MapByte) ToInt64(aa []byte, mapFn func(byte) int64) []int64 {
	bb := []int64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToInt8 maps a []Byte to a []Int8.
func (MapByte) ToInt8(aa []byte, mapFn func(byte) int8) []int8 {
	bb := []int8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToRune maps a []Byte to a []Rune.
func (MapByte) ToRune(aa []byte, mapFn func(byte) rune) []rune {
	bb := []rune{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToString maps a []Byte to a []String.
func (MapByte) ToString(aa []byte, mapFn func(byte) string) []string {
	bb := []string{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint maps a []Byte to a []Uint.
func (MapByte) ToUint(aa []byte, mapFn func(byte) uint) []uint {
	bb := []uint{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint16 maps a []Byte to a []Uint16.
func (MapByte) ToUint16(aa []byte, mapFn func(byte) uint16) []uint16 {
	bb := []uint16{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint32 maps a []Byte to a []Uint32.
func (MapByte) ToUint32(aa []byte, mapFn func(byte) uint32) []uint32 {
	bb := []uint32{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint64 maps a []Byte to a []Uint64.
func (MapByte) ToUint64(aa []byte, mapFn func(byte) uint64) []uint64 {
	bb := []uint64{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUint8 maps a []Byte to a []Uint8.
func (MapByte) ToUint8(aa []byte, mapFn func(byte) uint8) []uint8 {
	bb := []uint8{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}

// ToUintptr maps a []Byte to a []Uintptr.
func (MapByte) ToUintptr(aa []byte, mapFn func(byte) uintptr) []uintptr {
	bb := []uintptr{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
