// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xint8

// Do executes the test against a []Int8.
func (AllInt8) Do(aa []int8, test func(int8) bool) bool {
	for _, a := range aa {
		if !test(a) {
			return false
		}
	}
	return true
}
