// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xint8

// ToError maps a []Int8 to a []Error.
func (MapInt8) ToError(aa []int8, mapFn func(int8) error) []error {
	bb := []error{}
	for _, a := range aa {
		bb = append(bb, mapFn(a))
	}
	return bb
}
