// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package xint8

// MapInt8 contains methods for applying Map tranforms between Int8s and other types.
type MapInt8 struct{}

// Map provides access to MapInt8 methods.
var Map MapInt8
